export type Difficulty = 'easy' | 'medium' | 'hard';

export type QuizQuestion = {
  q: string;
  a: string[];
  c: number;
  d: Difficulty;
  e: string;
};

export type QuizCategory = 'web' | 'cpp' | 'dbms' | 'cricket' | 'india' | 'cs';

export const CATEGORY_LABELS: Record<QuizCategory, string> = {
  web: 'Web Development',
  cpp: 'C++',
  dbms: 'DBMS',
  cricket: 'Крикет',
  india: 'Индия (общие знания)',
  cs: 'Computer Science',
};

export const BANK: Record<QuizCategory, QuizQuestion[]> = {
  web: [
    {
      q: 'Which HTML tag is semantic and used for standalone content like a blog post?',
      a: ['<div>', '<section>', '<article>', '<span>'],
      c: 2,
      d: 'easy',
      e: '<article> represents independent, self-contained content.',
    },
    {
      q: 'Which CSS property enables smooth property transitions?',
      a: ['animation', 'transition', 'filter', 'transform'],
      c: 1,
      d: 'easy',
      e: 'transition animates changes between two values.',
    },
    {
      q: "What does CSS Grid 'grid-template-columns: repeat(3, 1fr);' do?",
      a: [
        'Creates 3 equal columns',
        'Creates 3 rows',
        'Repeats template vertically',
        'Sets fixed 3px columns',
      ],
      c: 0,
      d: 'medium',
      e: 'Defines three equal-width columns.',
    },
    {
      q: 'Which HTTP status indicates resource moved permanently?',
      a: ['200', '301', '302', '410'],
      c: 1,
      d: 'medium',
      e: '301 Moved Permanently.',
    },
    {
      q: 'Which attribute defers offscreen images?',
      a: ['defer', "loading='lazy'", 'async', "decoding='sync'"],
      c: 1,
      d: 'easy',
      e: 'Native lazy-loading.',
    },
    {
      q: 'Which method deep clones JSON-serializable data?',
      a: ['Object.assign', 'structuredClone', 'slice', 'map'],
      c: 1,
      d: 'medium',
      e: 'structuredClone for structured data.',
    },
    {
      q: 'Correct CSP to allow images from self and CDN?',
      a: [
        "img-src 'none' cdn.com",
        "img-src 'self' cdn.com",
        'default-src cdn.com',
        "script-src 'self' img.com",
      ],
      c: 1,
      d: 'hard',
      e: "img-src 'self' cdn.com",
    },
    {
      q: 'In React, memoize expensive calculations using:',
      a: ['useMemo', 'useEffect', 'useRef', 'useReducer'],
      c: 0,
      d: 'medium',
      e: 'useMemo.',
    },
    {
      q: 'Which CSS function clamps a value?',
      a: ['minmax()', 'clamp()', 'fit()', 'bound()'],
      c: 1,
      d: 'easy',
      e: 'clamp(min, preferred, max).',
    },
    {
      q: 'Service Workers primarily enable:',
      a: ['WebSockets', 'Offline caching & PWA', 'DOM parsing', 'SSR'],
      c: 1,
      d: 'medium',
      e: 'Offline-first caching.',
    },
  ],
  cpp: [
    {
      q: 'Which of the following is not a C++ storage class?',
      a: ['auto', 'register', 'volatile', 'mutable'],
      c: 2,
      d: 'medium',
      e: 'volatile is a type qualifier; storage classes are auto, register, static, extern.',
    },
    {
      q: 'What does RAII stand for?',
      a: [
        'Resource Acquisition Is Initialization',
        'Random Access Is Immediate',
        'Runtime Allocation Is Internal',
        'Reference And Instance Initialization',
      ],
      c: 0,
      d: 'hard',
      e: 'RAII ties resource lifetime to object lifetime.',
    },
    {
      q: 'Which keyword disables inheritance of virtual methods?',
      a: ['final', 'override', 'delete', 'static'],
      c: 0,
      d: 'medium',
      e: 'final prevents further overriding.',
    },
    {
      q: 'Which container guarantees contiguous storage?',
      a: ['std::list', 'std::deque', 'std::vector', 'std::map'],
      c: 2,
      d: 'easy',
      e: 'std::vector is contiguous.',
    },
    {
      q: 'Time complexity of std::unordered_map average lookup?',
      a: ['O(1)', 'O(log n)', 'O(n)', 'O(n log n)'],
      c: 0,
      d: 'easy',
      e: 'Average O(1).',
    },
    {
      q: 'Which feature avoids unnecessary copies when returning large objects?',
      a: ['Copy elision', 'SFINAE', 'CRTP', 'RTTI'],
      c: 0,
      d: 'medium',
      e: 'Return Value Optimization / copy elision.',
    },
    {
      q: "What does 'explicit' on a constructor prevent?",
      a: [
        'Slicing',
        'Implicit conversions',
        'Virtual dispatch',
        'Multiple inheritance',
      ],
      c: 1,
      d: 'medium',
      e: 'Prevents implicit conversions.',
    },
    {
      q: 'Which smart pointer expresses unique ownership?',
      a: ['shared_ptr', 'weak_ptr', 'unique_ptr', 'auto_ptr'],
      c: 2,
      d: 'easy',
      e: 'unique_ptr.',
    },
    {
      q: 'Which cast is safest for polymorphic downcast?',
      a: ['static_cast', 'reinterpret_cast', 'dynamic_cast', 'const_cast'],
      c: 2,
      d: 'medium',
      e: 'dynamic_cast checks at runtime.',
    },
    {
      q: "What does 'constexpr' enable?",
      a: [
        'Runtime-only eval',
        'Compile-time evaluation',
        'Dynamic linking',
        'Thread-local storage',
      ],
      c: 1,
      d: 'medium',
      e: 'Compile-time constants & functions.',
    },
  ],
  dbms: [
    {
      q: 'Which normal form removes transitive dependencies?',
      a: ['1NF', '2NF', '3NF', 'BCNF'],
      c: 2,
      d: 'medium',
      e: '3NF removes transitive deps.',
    },
    {
      q: 'Which SQL clause filters groups?',
      a: ['WHERE', 'GROUP BY', 'HAVING', 'ORDER BY'],
      c: 2,
      d: 'easy',
      e: 'HAVING filters aggregated groups.',
    },
    {
      q: 'Index type best for range queries?',
      a: ['Hash index', 'B+ Tree', 'Bitmap', 'Full-text'],
      c: 1,
      d: 'medium',
      e: 'B+ Trees support ranges efficiently.',
    },
    {
      q: "ACID: 'I' stands for:",
      a: ['Isolation', 'Integrity', 'Indexing', 'Idempotent'],
      c: 0,
      d: 'easy',
      e: 'Isolation.',
    },
    {
      q: 'Which anomaly is fixed by normalization?',
      a: ['Routing', 'Update anomaly', 'Sharding', 'Replication'],
      c: 1,
      d: 'easy',
      e: 'Normalization reduces anomalies.',
    },
    {
      q: 'In SQL, SELECT without ORDER BY returns rows in:',
      a: [
        'Insertion order',
        'Primary key order',
        'Random/unspecified order',
        'Clustered order',
      ],
      c: 2,
      d: 'medium',
      e: 'Unspecified order.',
    },
    {
      q: 'Which transaction isolation avoids dirty reads?',
      a: [
        'Read Uncommitted',
        'Read Committed',
        'Repeatable Read',
        'Serializable',
      ],
      c: 1,
      d: 'medium',
      e: 'Read Committed or stricter.',
    },
    {
      q: 'Foreign key enforces:',
      a: [
        'Entity integrity',
        'Referential integrity',
        'Domain integrity',
        'Semantic integrity',
      ],
      c: 1,
      d: 'easy',
      e: 'Referential integrity.',
    },
    {
      q: 'SQL to count distinct departments:',
      a: ['COUNT(dept)', 'COUNT(DISTINCT dept)', 'SUM(dept)', 'UNIQUE(dept)'],
      c: 1,
      d: 'easy',
      e: 'COUNT(DISTINCT col).',
    },
    {
      q: 'Denormalization typically:',
      a: [
        'Increases redundancy',
        'Decreases redundancy',
        'Prevents indexes',
        'Removes joins',
      ],
      c: 0,
      d: 'medium',
      e: 'It trades redundancy for speed.',
    },
  ],
  cricket: [
    {
      q: 'How many legal deliveries in a standard over?',
      a: ['5', '6', '8', '10'],
      c: 1,
      d: 'easy',
      e: '6 balls per over.',
    },
    {
      q: "MS Dhoni's role primarily was:",
      a: [
        'Opening batsman',
        'Leg spinner',
        'Wicket-keeper batsman',
        'All-rounder',
      ],
      c: 2,
      d: 'easy',
      e: 'Wicket-keeper + finisher.',
    },
    {
      q: 'A hat-trick means:',
      a: [
        '3 sixes in an over',
        '3 wickets in 3 balls',
        '3 fours in a row',
        '3 maidens',
      ],
      c: 1,
      d: 'easy',
      e: '3 wickets in consecutive balls.',
    },
    {
      q: 'Powerplay in ODIs initially allows how many fielders outside 30-yard circle?',
      a: ['2', '3', '4', '5'],
      c: 2,
      d: 'medium',
      e: 'Usually 4 in first Powerplay (rules can vary by period).',
    },
    {
      q: 'Which trophy is for Test cricket between India and Australia?',
      a: ['Border-Gavaskar', 'Ashes', 'Freedom Trophy', 'Trans-Tasman'],
      c: 0,
      d: 'easy',
      e: 'Border–Gavaskar Trophy.',
    },
    {
      q: 'DL/DLS method adjusts targets for:',
      a: ['Pitch conditions', 'Rain interruptions', 'No-balls', 'Tie-breakers'],
      c: 1,
      d: 'medium',
      e: 'Rain-affected games.',
    },
    {
      q: 'IPL franchise from Chennai?',
      a: ['MI', 'RCB', 'CSK', 'KKR'],
      c: 2,
      d: 'easy',
      e: 'Chennai Super Kings.',
    },
    {
      q: 'Maximum overs per bowler in a 50-over match?',
      a: ['8', '10', '12', '15'],
      c: 1,
      d: 'easy',
      e: '10 overs.',
    },
    {
      q: "Umpire's soft signal rule was:",
      a: [
        'Always out',
        "Field umpire's on-field call",
        'No longer used',
        'Only in Tests',
      ],
      c: 2,
      d: 'hard',
      e: 'Soft signal removed in recent updates.',
    },
    {
      q: 'Free hit follows:',
      a: ['Wide ball', 'No-ball', 'Dead ball', 'Leg byes'],
      c: 1,
      d: 'easy',
      e: 'No-ball.',
    },
  ],
  india: [
    {
      q: 'Capital of Jharkhand?',
      a: ['Ranchi', 'Jamshedpur', 'Dhanbad', 'Hazaribagh'],
      c: 0,
      d: 'easy',
      e: 'Ranchi.',
    },
    {
      q: 'Who wrote National Anthem of India?',
      a: [
        'Bankim Chandra',
        'Rabindranath Tagore',
        'Sarojini Naidu',
        'Subramania Bharati',
      ],
      c: 1,
      d: 'easy',
      e: 'Rabindranath Tagore.',
    },
    {
      q: 'Longest river flowing wholly in India?',
      a: ['Ganga', 'Yamuna', 'Godavari', 'Narmada'],
      c: 2,
      d: 'medium',
      e: 'Godavari is the longest within India.',
    },
    {
      q: 'First Indian in space?',
      a: [
        'Kalpana Chawla',
        'Rakesh Sharma',
        'Sunita Williams',
        'Vikram Sarabhai',
      ],
      c: 1,
      d: 'easy',
      e: 'Rakesh Sharma (1984).',
    },
    {
      q: 'State with highest literacy rate (recent data)?',
      a: ['Kerala', 'Tamil Nadu', 'Goa', 'Mizoram'],
      c: 0,
      d: 'medium',
      e: 'Kerala traditionally highest.',
    },
    {
      q: 'Dance form from Odisha?',
      a: ['Kathak', 'Bharatanatyam', 'Odissi', 'Kuchipudi'],
      c: 2,
      d: 'easy',
      e: 'Odissi.',
    },
    {
      q: 'Which is not a Union Territory?',
      a: ['Delhi', 'Puducherry', 'Sikkim', 'Ladakh'],
      c: 2,
      d: 'easy',
      e: 'Sikkim is a state.',
    },
    {
      q: 'Currency of India?',
      a: ['Rupee', 'Taka', 'Dinar', 'Baht'],
      c: 0,
      d: 'easy',
      e: 'INR.',
    },
    {
      q: 'Highest civilian award in India?',
      a: ['Padma Shri', 'Padma Bhushan', 'Padma Vibhushan', 'Bharat Ratna'],
      c: 3,
      d: 'easy',
      e: 'Bharat Ratna.',
    },
    {
      q: 'LOC is between India and:',
      a: ['China', 'Pakistan', 'Nepal', 'Bangladesh'],
      c: 1,
      d: 'medium',
      e: 'Line of Control with Pakistan.',
    },
  ],
  cs: [
    {
      q: 'Which structure gives O(1) average lookup?',
      a: ['Linked List', 'Hash Table', 'Binary Tree', 'Stack'],
      c: 1,
      d: 'easy',
      e: 'Hashing average O(1).',
    },
    {
      q: 'BST traversal yielding sorted order?',
      a: ['Preorder', 'Inorder', 'Postorder', 'Level-order'],
      c: 1,
      d: 'medium',
      e: 'Inorder.',
    },
    {
      q: 'Binary search complexity?',
      a: ['O(n)', 'O(log n)', 'O(n log n)', 'O(1)'],
      c: 1,
      d: 'easy',
      e: 'O(log n).',
    },
    {
      q: 'Semaphore used for:',
      a: [
        'Scheduling',
        'Mutual exclusion/sync',
        'Paging',
        'Deadlock detection',
      ],
      c: 1,
      d: 'medium',
      e: 'Sync for shared resources.',
    },
    {
      q: 'TCP guarantees:',
      a: [
        'Best-effort',
        'Connectionless',
        'Ordered, reliable delivery',
        'Broadcast',
      ],
      c: 2,
      d: 'medium',
      e: 'Reliable, ordered.',
    },
    {
      q: "Dijkstra's algorithm paradigm:",
      a: ['Greedy', 'Divide & Conquer', 'DP', 'Backtracking'],
      c: 0,
      d: 'medium',
      e: 'Greedy.',
    },
    {
      q: 'Which normal form removes transitive deps?',
      a: ['1NF', '2NF', '3NF', 'BCNF'],
      c: 2,
      d: 'hard',
      e: '3NF.',
    },
    {
      q: 'Pattern hiding complex subsystems:',
      a: ['Observer', 'Strategy', 'Decorator', 'Facade'],
      c: 3,
      d: 'medium',
      e: 'Facade.',
    },
    {
      q: 'Git create and switch branch:',
      a: [
        'git switch',
        'git checkout -b <name>',
        'git new <name>',
        'git branch -s',
      ],
      c: 1,
      d: 'easy',
      e: 'checkout -b (or switch -c).',
    },
    {
      q: 'Quicksort average case:',
      a: ['O(n)', 'O(n log n)', 'O(n^2)', 'O(log n)'],
      c: 1,
      d: 'medium',
      e: 'O(n log n).',
    },
  ],
};
